name = "Users"
description = "Show user endpoint"

[variables]
id = "1"
token = "123"

[request]
url = "https://httpbin.org/get"
method = "GET"

[request.headers]
content-type = "application/json"
authorization = "Bearer {{ token }}"
