name = "Users"
description = "Create user endpoint"

[variables]
token = "123"

[request]
url = "http://test.com/users"
method = "POST"
body = """
{
  "data": {
    "attributes": {
      "name": "Bob"
    }
  }
}
"""

[request.headers]
content-type = "application/json"
authorization = "Bearer {{ token }}"
