name = "Users"
description = "Create user endpoint"

[variables]
id = 1
token = "123"

[request]
url = "https://httpbin.org/anything/{{id}}"
method = "POST"
body = """
{
  "data": {
    "attributes": {
      "name": "Bob",
      "id": "{{id}}"
    }
  }
}
"""

[request.headers]
content-type = "application/json"
authorization = "Bearer {{token}}"
