# Build the mdbook docs and deploy them to GitHub Pages.
name: Web

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  web:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: latest

      - name: Build mdbook
        run: mdbook build docs

      - name: Check HTML for broken internal links
        uses: untitaker/hyperlink@0.1.29
        with:
          args: docs/book/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: docs/book
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
